### ISSUE TITLE
Initial Implementation of react-ga

### ISSUE THREAD

**Issue by niteshkumar2000** [FreakyOS/website#2]
This issue just focuses on initial implementation of the google analytics with react, Any help/request can be commented on this issue's thread

**Comment by niteshkumar2000** [comment]
https://levelup.gitconnected.com/using-google-analytics-with-react-3d98d709399b

Hey @jeivardan, I found this article really useful, I think this should be enough for initial quick start. Let's focus on this!

**Comment by jeivardan** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/36626247/88021076-75a53080-cb4a-11ea-8860-522fa2068340.png)
What to do about the url?

**Comment by niteshkumar2000** [comment]
Use https://freakyos.github.io/FreakySite

* Even though we are testing with local environment, finally it's gonna be implemented on gh pages so it will be better if we use existing gh pages URL

**Comment by niteshkumar2000** [comment]
@jeivardan make sure these tokens are put in a config file and fetched from there, we always should not hard code values

step1: https://github.com/DAMCS/hack-in/blob/master/.env.development
step2: https://github.com/DAMCS/hack-in/blob/master/src/App.js#L9
Just check with the DAMCS project and use it as reference! 😊

step3: try hitting the page and check the google analytics window if the it's visible if so it's verified and we are ready to merge

**Comment by niteshkumar2000** [comment]
http://freakyos.xyz/c/FreakyOS/FreakySite/+/994

commit c8d2515fa7ec76d77f41ca18b02787283e6ae589 code review done and verified and merged :)
It's a good start!

**Comment by jeivardan** [comment]
**Initial implementation of Google Analytics done and tested**
![Screenshot (10)](https://user-images.githubusercontent.com/36626247/88030102-71800f80-cb58-11ea-9483-16bcb8389b3a.png)

**Comment by niteshkumar2000** [comment]
Really nice :)
