### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by niteshkumar2000** [FreakyOS/website#3]
We have to integrate travis ci into the project for continuous integration.

Use Case:
*  If a commit is pushed to master branch travis ci just fetches the latest commit HEAD from the specified branch and run the test scripts and deploys to the gh-pages.
* No need to trigger test scripts and use npm run deploy every single time before we deploy to production.
* In this way we can automate the deployment process :)

**Comment by niteshkumar2000** [comment]
https://medium.com/@sumn2u/automate-create-react-app-deployment-to-gh-pages-using-travis-ci-b2a97203680b

Yo! @jeivardan This article seems to be good for initial start, Let's try it out when we get free time :)

**Comment by aakashhemadri** [comment]
@niteshkumar2000 I am willing to pick this will put up a pull request

**Comment by niteshkumar2000** [comment]
> @niteshkumar2000 I am willing to pick this will put up a pull request
> 

Yeah sure but no need to PR! Better push it to gerrit :)

**Comment by niteshkumar2000** [comment]
Thanks @aakashhemadri will add github token to travis, hope it will start the build automatically :)
I'm Closing this issue!

Commit :- c7d96f2e82413ee9ee4bcbe33efe24af08d454f8
Code-review :- http://freakyos.xyz/c/FreakyOS/FreakySite/+/1133/3
